# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

  config.vm.define :secondary1 do |server|
    server.vm.network :private_network, ip: "192.168.42.101"
  end

  config.vm.define :secondary2 do |server|
    server.vm.network :private_network, ip: "192.168.42.102"
  end
  
  config.vm.define :primary do |server|
    server.vm.network :private_network, ip: "192.168.42.100"
  end

  config.vm.define :arbiter do |server|
    server.vm.network :private_network, ip: "192.168.42.110"
  end

  config.vm.define :delayed_secondary do |server|
    server.vm.network :private_network, ip: "192.168.42.111"
  end
end
