- name: Reconfigure MongoDB to listen on all interfaces
  lineinfile:
    path: /etc/mongod.conf
    regexp: '^  bindIp:'
    line: "  bindIp: 0.0.0.0"
  register: mongodb_config

- name: Start and enable mongod service
  service:
    name: mongod
    state: started
    enabled: yes

- name: Restart MongoDB
  service:
    name: mongod
    state: restarted
  when: mongodb_config.changed

- block:
  - name: Add ReplicaSet to MongoDB configuration
    blockinfile:
      path: /etc/mongod.conf
      marker: "### {mark} ANSIBLE MANAGED BLOCK ReplicaSet of MongoDB"
      block: "replication.replSetName: {{replicaset_name}}"
    register: mongodb_config

  - name: Restart MongoDB
    service:
      name: mongod
      state: restarted
    when: mongodb_config.changed

  - name: Waiting for server initialization
    pause:
      seconds: 13
    when: mongodb_config.changed

  - name: Check replica set status
    shell: |
      mongo --eval 'rs.status().ok;' --host "{{groups.mongo_replicaset[0]}}"
    register: rs_status

  - block:
    - name: Initialize the replica set
      shell: |
        mongo --eval 'rs.initiate({_id: "{{replicaset_name}}", members:[{_id: 0, host: "{{inventory_hostname}}:27017"}]});' --host "{{groups.mongo_replicaset[0]}}"
      when: inventory_hostname == groups.mongo_replicaset[0]

    - name: Waiting for ReplicaSet Initialization
      pause:
        seconds: 13
      when: inventory_hostname == groups.mongo_delayed_replica[0]

    - name: Add rest of ReplicaSet members
      shell: /usr/bin/mongo --eval 'rs.add("{{ inventory_hostname }}:27017");' --host "{{groups.mongo_replicaset[0]}}"
      delegate_to: "{{groups.mongo_replicaset[0]}}"
    when: rs_status.stdout_lines[-1] == "0" # no RS set yet

  - block:
    - name: Add ReplicaSet members
      shell: |
        /usr/bin/mongo --eval 'rs.add("{{ inventory_hostname }}:27017");' --host "{{replicaset_name}}/{{groups.mongo_replicaset|join(',')}}"
    when: rs_status.stdout_lines[-1] == "1" # a RS already exists

  when: replicaset_enabled is defined and replicaset_enabled == true

- block:
  - name: Create directory for tuned profile
    file:
      path: /etc/tuned/no-thp
      state: directory
  
  - name: Create tuned profile to disable Tuned Huge Page
    copy:
      src: files/tuned.conf
      dest: /etc/tuned/no-thp/tuned.conf
  
  - name: Enable tuned no-thp profile
    shell: tuned-adm profile no-thp
    become: true

  when: optimize_OS_mongodb is defined and optimize_OS_mongodb == true

- name: Set host as delayed replica
  shell: /usr/bin/mongo --eval 'cfg=rs.config(); cfg.members.forEach(member => { if("{{inventory_hostname}}:27017"==member.host){ cur_id=member._id; cfg.members[cur_id].slaveDelay={{replica_delay}}; cfg.members[cur_id].hidden=true; cfg.members[cur_id].priority=0; rs.reconfig(cfg);  }})' --host "{{replicaset_name}}/{{groups.mongo_replicaset|join(',')}}"
  when:
    - replicaset_enabled is defined
    - replicaset_enabled == true
    - replica_delay is defined
    - replica_delay > 0
